# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 461, 661))
        self.widget.setStyleSheet("\n"
"background-color: rgb(46, 79, 79);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(110, 30, 241, 131))
        font = QtGui.QFont()
        font.setFamily("SF Pro Rounded")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(221, 165, 51);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 421, 311))
        self.label_2.setStyleSheet('image: url("C:/Users/Amel/Desktop/homepage+controls/ICONS/R1.png");')
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(410, 0, 491, 661))
        self.widget_2.setStyleSheet("\n"
"background-color: rgb(46, 79, 79);")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 331, 131))
        font = QtGui.QFont()
        font.setFamily("SF Pro Rounded")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"font: 81 28pt \"SF Pro Rounded\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 331, 131))
        font = QtGui.QFont()
        font.setFamily("SF Pro Rounded")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(221, 165, 51);\n"
"background-color: transparent;\n"
"font: 81 28pt \"SF Pro Rounded\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 421, 211))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"font: 9pt \"SF Pro Display\";")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.start_bt = QtWidgets.QPushButton(self.widget_2)
        self.start_bt.setGeometry(QtCore.QRect(60, 420, 381, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Rounded")
        font.setPointSize(10)
        self.start_bt.setFont(font)
        self.start_bt.setStyleSheet("background-color: rgb(223, 166, 51);\n"
"\n"
"")
        self.start_bt.setFlat(False)
        self.start_bt.setObjectName("start_bt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Robot"))
        self.label_3.setText(_translate("MainWindow", "TECHNOLOGY"))
        self.label_4.setText(_translate("MainWindow", "WAY OF NEW"))
        self.label_5.setText(_translate("MainWindow", "Welcome to our robot control app ! Our user-friendly interface makes it easy to maneuver your robot with precision and accuracy. You can control its movements, adjust its settings, and even access its camera feed to see what\'s happening in real-time.But that\'s not all - our app also includes advanced features like scheduling and automation, so you can program your robot to perform tasks on its own."))
        self.start_bt.setText(_translate("MainWindow", "Start"))
